
default: &default
  adapter: postgresql
  secret_key_base: ca769b0d049946f9e56b15fae3e75aa2f3e391d5832594910ac7219a20faa9ea92c2822e33d406784114ee4c5ecda9b603b00d317a6353b94b44992567e86a8c
  database: postgres://rails:a7QqzdpWNMD5j5f8Qujo2l3EilQTLrvw@dpg-ckt4i68168ec73d603d0-a.singapore-postgres.render.com/house_market_place_pj5w
  username: rails
  password: a7QqzdpWNMD5j5f8Qujo2l3EilQTLrvw

development:
  <<: *default

production:
  <<: *default
